name: Test (presets)

on:
  pull_request:
    branches: [ presets ]
  workflow_call:
    inputs:
      ref:
        type: string
      repo:
        type: string

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: master
      - name: Setup NodeJS
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.0.0
        with:
          node-version: 20
          cache: "npm"
      - name: Setup metrics
        run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Run tests
        run: npm run test-presets
        env:
          HEAD_REF: ${{ inputs.ref }}
          REPO: ${{ inputs.repo }}
