name: Build, test and analyze

on:
  pull_request:
    branches: [ master ]
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  # Run linter to ensure new code respect coding rules
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.0.0
        with:
          node-version: 20
          cache: 'npm'
      - name: Setup metrics
        run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Check contributions requirements
        run: npm run test-contrib
      - name: Run linter
        run: npm run linter
      - name: Format code
        run: |
          mkdir -v -p /home/runner/.cache/dprint/cache
          npm exec dprint check -- --config .github/config/dprint.json

  # Build docker image from branch and run tests
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.0.0
        with:
          persist-credentials: false
      - name: Build gh-metrics/metrics:${{ github.head_ref || 'master' }}
        env:
          GIT_REF: ${{ github.head_ref || 'master' }}
        run: docker build -t gh-metrics/metrics:$(echo $GIT_REF | sed 's/[^a-z]/-/g') .
      - name: Run tests
        env:
          GIT_REF: ${{ github.head_ref || 'master' }}
        run: docker run --rm --entrypoint="" gh-metrics/metrics:$(echo $GIT_REF | sed 's/[^a-z]/-/g') npm run test-metrics
